version: "3"

services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    environment:
      - node.name=opensearch-node
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - opensearch.ssl.verificationMode=none
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600" # for monitoring
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601"
    networks:
      - opensearch-network

volumes:
  opensearch-data:

networks:
  opensearch-network:
